version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    rules:
      - path: internal/service/generate-excel/
        linters:
          - errcheck
          - "-QF1003"
          - "-QF1008"
          - "-QF1011"
          - "-S1002"