version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    rules:
      - path: internal/service/generate-excel/
        linters:
          - errcheck