services:
  mysql:
    image: mysql:8.0.46

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aaaa
      MYSQL_USER: valera
      MYSQL_PASSWORD: pass

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  migrate:
    build: .

    env_file:
      - .env

    environment:
      CONFIG_PATH: /app/config/docker.yaml

    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations

    command: ["./migrate"]

    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build: .

    env_file:
      - .env

    environment:
      CONFIG_PATH: /app/config/docker.yaml

    volumes:
      - ./config:/app/config

    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  mysql-data: