env: "prod"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s

parse_time: true
migration_path: "./migrations"

jwt:
  expiration_hours: 24

auth:
  provider: "config"
  admin_permission:
    - "admin"