env: "local"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

db_user: ""
db_password: ""
db_host: "localhost"
db_port: 3306
db_name: ""

parse_time: true
migration_path: "./migrations"

admin_login: ""
admin_pass: ""

jwt:
  secret: ""
  expiration_hours: 24

auth:
  provider: "config"
  admin_permission:
    - "admin"